use bevy::prelude::*;
use std::collections::HashMap;

use crate::content::item::components::{ItemComponents, PlacesBlock};
use crate::content::item::display::ItemDisplay;
use crate::content::substance::{PartID, SubstanceID};
use crate::voxel::{BlockID, ItemID};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SECTION 1 – ITEM DEFINITIONS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// What kind of thing this item is.
#[derive(Clone, Debug)]
pub enum ItemKind {
    /// Can be placed into the world as a block.
    Block { block_id: BlockID },
    /// Pure resource — ore, wire, circuit board, etc.
    Resource,
    /// A tool with optional durability cap.
    Tool { max_durability: Option<u32> },
    /// Generated by the substance × part cross product.
    SubstancePart { substance: SubstanceID, part: PartID },
}

impl Default for ItemKind {
    /// The default kind of item is just a resource.
    fn default() -> Self {
        ItemKind::Resource
    }
}

pub struct ItemDefinition {
    pub name:         String,
    pub display_name: String,
    pub max_stack:    u16,       // e.g. 99 for ore, 1 for unique tools
    pub kind:         ItemKind,
    pub display:      ItemDisplay,
    pub components:   ItemComponents,
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SECTION 2 – ITEM REGISTRY
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Mirror of `BlockRegistry` — same pattern.
#[derive(Resource)]
pub struct ItemRegistry {
    items: Vec<ItemDefinition>,
    /// Fast reverse lookup: BlockID → the item that places it
    block_to_item: HashMap<BlockID, ItemID>,
    /// Stable-by-name lookup
    name_to_item: HashMap<String, ItemID>,
}

impl ItemRegistry {
    pub fn new() -> Self {
        Self {
            items: Vec::new(),
            block_to_item: HashMap::new(),
            name_to_item: HashMap::new(),
        }
    }

    pub fn get(&self, id: ItemID) -> &ItemDefinition {
        &self.items[id.0 as usize]
    }

    pub fn by_block(&self, block: BlockID) -> Option<ItemID> {
        self.block_to_item.get(&block).copied()
    }

    pub fn by_name(&self, name: String) -> Option<ItemID> {
        self.name_to_item.get(&name).copied()
    }

    pub fn register(&mut self, def: ItemDefinition) -> ItemID {
        let id = ItemID(self.items.len() as u16);
        let name = def.name.clone();

        // If this item places a block, record the reverse link
        if let ItemKind::Block { block_id } = def.kind {
            self.block_to_item.insert(block_id, id);
        }

        // WIP: we're currently moving over to ItemComponents
        if let Some(pb) = def.components.get::<PlacesBlock>() {
            self.block_to_item.insert(pb.block_id, id);
        }

        self.items.push(def);
        self.name_to_item.insert(name, id);
        id
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Every id in registration order. IDs are dense from 0, which is what
    /// makes name suggestions and tab completion a plain scan.
    pub fn ids(&self) -> impl Iterator<Item = ItemID> {
        (0..self.items.len() as u16).map(ItemID)
    }
}

impl Default for ItemRegistry {
    fn default() -> Self { Self::new() }
}
