use bevy::prelude::*;
use std::collections::HashMap;

use crate::plugin::geometry::model::ModelArena;
use crate::plugin::item::components::*;
use crate::plugin::loader::block_registry::{BlockID, BlockRegistry};
use crate::plugin::loader::substance_registry::{SubstanceID, PartID};
use crate::plugin::ui::item::ItemDisplay;
use crate::plugin::inventory::main::MAX_STACK;
use crate::plugin::loader::block_icons::{BlockIcons, icon_voxel};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ITEM DEFINITIONS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct ItemID(pub u16);

/// What kind of thing this item is.
#[derive(Clone, Debug)]
pub enum ItemKind {
    /// Can be placed into the world as a block.
    /// The block_id field is the ID of the block that will be created.
    Block { block_id: BlockID },
    /// Pure resource — ore, wire, circuit board, etc.
    Resource,
    /// A tool with optional durability cap.
    Tool { max_durability: Option<u32> },
    /// Generated by the substance × part cross product.
    SubstancePart { substance: SubstanceID, part: PartID },
}

impl Default for ItemKind {
    /// The default kind of item is just a resource.
    fn default() -> Self {
        ItemKind::Resource
    }
}

pub struct ItemDefinition {
    pub name:         String,
    pub display_name: String,
    pub max_stack:    u16,       // e.g. 99 for ore, 1 for unique tools
    pub kind:         ItemKind,
    pub display:      ItemDisplay,
    pub components:   ItemComponents,
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ITEM REGISTRY
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Mirror of BlockRegistry — same pattern.
#[derive(Resource)]
pub struct ItemRegistry {
    items: Vec<ItemDefinition>,
    /// Fast reverse lookup: BlockID → the item that places it
    block_to_item: HashMap<BlockID, ItemID>,
    /// Stable-by-name lookup
    name_to_item: HashMap<String, ItemID>,
}

impl ItemRegistry {
    pub fn new() -> Self {
        Self { 
            items: Vec::new(),
            block_to_item: HashMap::new(),
            name_to_item: HashMap::new(),
        }
    }

    pub fn get(&self, id: ItemID) -> &ItemDefinition {
        &self.items[id.0 as usize]
    }

    pub fn by_block(&self, block: BlockID) -> Option<ItemID> {
        self.block_to_item.get(&block).copied()
    }

    pub fn by_name(&self, name: String) -> Option<ItemID> {
        self.name_to_item.get(&name).copied()
    }

    pub fn register(&mut self, def: ItemDefinition) -> ItemID {
        let id = ItemID(self.items.len() as u16);
        let name = def.name.clone();

        // If this item places a block, record the reverse link
        if let ItemKind::Block { block_id } = def.kind {
            self.block_to_item.insert(block_id, id);
        }

        // WIP: we're currently moving over to ItemComponents
        if let Some(pb) = def.components.get::<PlacesBlock>() {
            self.block_to_item.insert(pb.block_id, id);
        }

        self.items.push(ItemDefinition { ..def });
        self.name_to_item.insert(name, id);
        id
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Loading Systems
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Hardcoded block-placing item registry initialization.
/// Scans the entire block registry and generates a suitable item from the block
/// definition that is capable of placing the block in the world.
/// TODO: add a way to inject additional item components on the item from block def.

pub fn populate_item_registry_from_blocks_sys(
    block_registry: Res<BlockRegistry>,
    mut item_registry: ResMut<ItemRegistry>,
    mut block_icons: ResMut<BlockIcons>,
    arena: Res<ModelArena>,
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
) {
    // id 0 is air — no block, no icon, no item.
    for id in 1..block_registry.size() {
        let block_id = BlockID(id as u16);
        let block = block_registry.get(block_id);
 
        let voxel = icon_voxel(&block.shape, block_id);
        let icon = block_icons.ensure(voxel, &block_registry, &arena, &mut images, &mut meshes);
 
        item_registry.register(ItemDefinition {
            name: block.name.clone(),
            display_name: block.display_name.clone(),
            max_stack: MAX_STACK,
            kind: ItemKind::Block { block_id },
            display: ItemDisplay::Image { image: icon },
            components: ItemComponents::default().with(PlacesBlock { block_id }),
        });
    }
 
    bevy::log::info_once!(
        "ItemRegistry populated from blocks: {} entries.",
        item_registry.len()
    );
}
